// Re-apply this project's Android tweaks to the generated `android/` folder.
//
// `android/` is gitignored and regenerated by `npx cap add android`, which resets it to
// Capacitor defaults. This script re-applies (idempotently) everything we depend on:
// Gradle/AGP/SDK versions, Play Games manifest entries, landscape lock, the launcher icon,
// and a fullscreen/immersive MainActivity. Why each exists: docs/capacitor-android.md.
//
//   npm install
//   npm run build:www                 # build www/ (its index.html carries the <head> the Capacitor bridge needs)
//   npx cap add android               # generate android/ (copies www/)
//   npm run setup:android             # <-- this script
//   npx cap sync android              # re-copy web + plugins, then build the APK
//
// Idempotent: safe to run repeatedly. local.properties + buildToolsVersion are derived from
// ANDROID_HOME so the script stays portable across machines.
import { readFileSync, writeFileSync, copyFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const A = join(ROOT, 'android');

// Combo verified on JDK 21 + SDK 36 (tune here if the toolchain moves):
const AGP = '8.7.2', GRADLE = '8.9', COMPILE_SDK = 36, TARGET_SDK = 36, MIN_SDK = 23;
const PGS_APP_ID = '533472253687'; // docs/play-games-setup.md
const APP_VERSION = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version; // Android versionName = эта версия (база сравнения Capgo OTA)

const MAIN_ACTIVITY = `package com.planeflow.game;

import android.os.Bundle;
import androidx.core.view.WindowCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.core.view.WindowInsetsControllerCompat;
import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {
    // Fullscreen (immersive): hide status + nav bars; they return transiently on edge-swipe.
    @Override
    public void onCreate(Bundle savedInstanceState) {
        // Регистрируем плагины ДО super.onCreate — требование Capacitor.
        registerPlugin(SnapshotsPlugin.class);
        registerPlugin(InstallReferrerPlugin.class);
        registerPlugin(FirebaseAnalyticsPlugin.class);
        super.onCreate(savedInstanceState);
        hideSystemBars();
    }

    @Override
    public void onWindowFocusChanged(boolean hasFocus) {
        super.onWindowFocusChanged(hasFocus);
        if (hasFocus) hideSystemBars();
    }

    private void hideSystemBars() {
        WindowCompat.setDecorFitsSystemWindows(getWindow(), false);
        WindowInsetsControllerCompat controller =
            new WindowInsetsControllerCompat(getWindow(), getWindow().getDecorView());
        controller.hide(WindowInsetsCompat.Type.systemBars());
        controller.setSystemBarsBehavior(
            WindowInsetsControllerCompat.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);
    }
}
`;

// Тонкий мост к Google Play Saved Games (Snapshots) поверх PGS v2. JS видит его как
// window.Capacitor.Plugins.Snapshots (методы load/save) — см. src/game/12c-cloud-saves.ts.
// Вход в Play Games (app-wide singleton) обеспечивает @openforge/capacitor-game-connect;
// сюда мы попадаем только ПОСЛЕ Account.signIn(). Конфликт версий резолвится автоматически
// политикой "most recently modified" (= last-writer-wins). Артефакт play-services-games-v2
// добавляется в app/build.gradle ниже (на компил-classpath app-модуля).
const SNAPSHOTS_PLUGIN = `package com.planeflow.game;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import com.google.android.gms.games.PlayGames;
import com.google.android.gms.games.SnapshotsClient;
import com.google.android.gms.games.snapshot.Snapshot;
import com.google.android.gms.games.snapshot.SnapshotMetadataChange;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

@CapacitorPlugin(name = "Snapshots")
public class SnapshotsPlugin extends Plugin {

    private static final String SNAPSHOT_NAME = "planeflow_progress_v1";

    @PluginMethod
    public void load(final PluginCall call) {
        final SnapshotsClient client;
        try { client = PlayGames.getSnapshotsClient(getActivity()); }
        catch (Exception e) { call.reject("snapshots client unavailable: " + e.getMessage()); return; }

        client.open(SNAPSHOT_NAME, true, SnapshotsClient.RESOLUTION_POLICY_MOST_RECENTLY_MODIFIED)
            .addOnFailureListener(e -> call.reject("open failed: " + e.getMessage()))
            .addOnSuccessListener(result -> {
                // Политика "most recently modified" авторезолвит конфликт уже на open(),
                // поэтому здесь ждём данные, а не конфликт (на всякий случай — явный reject).
                if (result.isConflict()) { call.reject("unexpected conflict on open"); return; }
                Snapshot snapshot = result.getData();
                try {
                    byte[] bytes = snapshot.getSnapshotContents().readFully();
                    JSObject ret = new JSObject();
                    ret.put("data", (bytes == null || bytes.length == 0)
                        ? null : new String(bytes, StandardCharsets.UTF_8));
                    client.discardAndClose(snapshot);   // read-only: освобождаем снапшот без записи
                    call.resolve(ret);
                } catch (IOException e) {
                    call.reject("read failed: " + e.getMessage());
                }
            });
    }

    @PluginMethod
    public void save(final PluginCall call) {
        final String data = call.getString("data");
        if (data == null) { call.reject("missing 'data'"); return; }

        final SnapshotsClient client;
        try { client = PlayGames.getSnapshotsClient(getActivity()); }
        catch (Exception e) { call.reject("snapshots client unavailable: " + e.getMessage()); return; }

        client.open(SNAPSHOT_NAME, true, SnapshotsClient.RESOLUTION_POLICY_MOST_RECENTLY_MODIFIED)
            .addOnFailureListener(e -> call.reject("open failed: " + e.getMessage()))
            .addOnSuccessListener(result -> {
                if (result.isConflict()) { call.reject("unexpected conflict on open"); return; }
                Snapshot snapshot = result.getData();
                snapshot.getSnapshotContents().writeBytes(data.getBytes(StandardCharsets.UTF_8));
                client.commitAndClose(snapshot, SnapshotMetadataChange.EMPTY_CHANGE)
                    .addOnSuccessListener(meta -> { JSObject ret = new JSObject(); ret.put("ok", true); call.resolve(ret); })
                    .addOnFailureListener(e -> call.reject("commit failed: " + e.getMessage()));
            });
    }
}
`;

// Тонкий мост к Google Play Install Referrer API.
// JS видит его как window.Capacitor.Plugins.InstallReferrer (метод get).
// Возвращает {referrer: string} — UTM/referrer-строка из магазина, либо пустая строка.
// Захватывается один раз при первом запуске после установки (src/game/12d-consent.ts).
const INSTALL_REFERRER_PLUGIN = `package com.planeflow.game;

import android.content.Context;
import com.android.installreferrer.api.InstallReferrerClient;
import com.android.installreferrer.api.InstallReferrerStateListener;
import com.android.installreferrer.api.ReferrerDetails;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

@CapacitorPlugin(name = "InstallReferrer")
public class InstallReferrerPlugin extends Plugin {

    @PluginMethod
    public void get(final PluginCall call) {
        Context ctx = getContext();
        InstallReferrerClient client = InstallReferrerClient.newBuilder(ctx).build();
        client.startConnection(new InstallReferrerStateListener() {
            @Override
            public void onInstallReferrerSetupFinished(int responseCode) {
                JSObject ret = new JSObject();
                if (responseCode == InstallReferrerClient.InstallReferrerResponse.OK) {
                    try {
                        ReferrerDetails details = client.getInstallReferrer();
                        ret.put("referrer", details.getInstallReferrer());
                    } catch (Exception e) {
                        ret.put("referrer", "");
                    }
                } else {
                    ret.put("referrer", "");
                }
                client.endConnection();
                call.resolve(ret);
            }

            @Override
            public void onInstallReferrerServiceDisconnected() {
                JSObject ret = new JSObject();
                ret.put("referrer", "");
                call.resolve(ret);
            }
        });
    }
}
`;

// Тонкий мост к Firebase Analytics SDK.
// JS видит его как window.Capacitor.Plugins.FirebaseAnalytics (метод logEvent).
// Автоматически инициализируется из google-services.json при старте приложения.
// Используется в src/game/12e-firebase-sink.ts как замена console-sink для PFAnalytics.
const FIREBASE_ANALYTICS_PLUGIN = `package com.planeflow.game;

import android.os.Bundle;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;
import com.google.firebase.analytics.FirebaseAnalytics;

@CapacitorPlugin(name = "FirebaseAnalytics")
public class FirebaseAnalyticsPlugin extends Plugin {

    private FirebaseAnalytics fa;

    @Override
    public void load() {
        fa = FirebaseAnalytics.getInstance(getContext());
    }

    @PluginMethod
    public void logEvent(final PluginCall call) {
        String name = call.getString("name");
        if (name == null || name.isEmpty()) { call.reject("missing name"); return; }

        JSObject paramsObj = call.getObject("params");
        Bundle bundle = new Bundle();
        if (paramsObj != null) {
            java.util.Iterator<String> keys = paramsObj.keys();
            while (keys.hasNext()) {
                String k = keys.next();
                try {
                    Object v = paramsObj.get(k);
                    if (v instanceof String)  bundle.putString(k, (String) v);
                    else if (v instanceof Number) bundle.putDouble(k, ((Number) v).doubleValue());
                    else if (v instanceof Boolean) bundle.putBoolean(k, (Boolean) v);
                } catch (org.json.JSONException ignored) {}
            }
        }
        fa.logEvent(name, bundle);
        JSObject ret = new JSObject(); ret.put("ok", true);
        call.resolve(ret);
    }
}
`;

// ProGuard/R8 keep-правила для RELEASE-шринка (Фаза 3, docs/memory-android17.md).
// R8 в релизе минифицирует и переименовывает код; наши Capacitor-плагины мост зовёт
// РЕФЛЕКСИЕЙ по имени класса/метода (@CapacitorPlugin / @PluginMethod), поэтому их надо
// явно сохранить — иначе Snapshots/InstallReferrer/FirebaseAnalytics молча отвалятся в
// релизе. Capacitor-core, play-services и firebase несут свои consumer-правила в AAR,
// их держать не нужно. Наши классы все в пакете com.planeflow.game — сохраняем целиком.
const PROGUARD_RULES = `# planeflow — генерируется scripts/setup-android.mjs (Фаза 3, docs/memory-android17.md).
# R8-шринк релиза не должен трогать Capacitor-плагины (мост зовёт их рефлексией по имени).
-keep @com.getcapacitor.annotation.CapacitorPlugin public class * { *; }
-keepclassmembers class * { @com.getcapacitor.annotation.PluginMethod <methods>; }
# Наши плагины и MainActivity (регистрируются по классу; методы — рефлексией).
-keep class com.planeflow.game.** { *; }
# Crashlytics: R8 full-mode strips line numbers by default — without this, crash stack
# traces from the field are useless even after de-obfuscation with the uploaded mapping file.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile
`;

// Явный запрет cleartext-трафика (docs/play-featuring-plan.md, Privacy & Security). Всё, с чем
// говорит приложение (Firebase, Play Games, Capgo OTA), уже HTTPS — этот файл просто закрывает
// дефолтный Android-фолбэк на cleartext явным запретом, ничего не меняя в поведении.
const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
</network-security-config>
`;

if (!existsSync(A)) {
  console.error('android/ not found — run `npx cap add android` first.');
  process.exit(1);
}

const log = (m) => console.log('  ' + m);

function patch(rel, fn) {
  const p = join(A, rel);
  if (!existsSync(p)) { log(`skip (missing): ${rel}`); return; }
  const before = readFileSync(p, 'utf8');
  const after = fn(before);
  if (after != null && after !== before) { writeFileSync(p, after); log(`patched: ${rel}`); }
  else log(`unchanged: ${rel}`);
}

function highestBuildTools() {
  const sdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
  if (!sdk) return null;
  const dir = join(sdk, 'build-tools');
  if (!existsSync(dir)) return null;
  const vs = readdirSync(dir).filter((x) => /^\d+\./.test(x))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
  return vs.length ? vs[vs.length - 1] : null;
}

console.log('setup-android: patching android/ …');

// 1) Gradle / AGP / SDK levels
patch('variables.gradle', (s) => s
  .replace(/minSdkVersion\s*=\s*\d+/, `minSdkVersion = ${MIN_SDK}`)
  .replace(/compileSdkVersion\s*=\s*\d+/, `compileSdkVersion = ${COMPILE_SDK}`)
  .replace(/targetSdkVersion\s*=\s*\d+/, `targetSdkVersion = ${TARGET_SDK}`));

patch('build.gradle', (s) => s
  .replace(/com\.android\.tools\.build:gradle:[\d.]+/, `com.android.tools.build:gradle:${AGP}`));

patch('gradle/wrapper/gradle-wrapper.properties', (s) => s
  .replace(/gradle-[\d.]+-(all|bin)\.zip/, `gradle-${GRADLE}-all.zip`));

patch('app/build.gradle', (s) => {
  if (/buildToolsVersion/.test(s)) return s;
  const bt = highestBuildTools();
  if (!bt) { log('build-tools not detected (set ANDROID_HOME) — leaving AGP default'); return s; }
  return s.replace(/(compileSdkVersion\s+rootProject\.ext\.compileSdkVersion[^\n]*\n)/,
    `$1    buildToolsVersion "${bt}"\n`);
});

// Capgo OTA: versionName = версия из package.json (Capacitor по умолчанию ставит "1.0").
// Нативная версия — база сравнения Capgo: бандл доставляется, только если он ВЫШЕ неё.
// CI шлёт бандлы как MAJOR.MINOR.<run_number> (deploy.yml), т.е. заведомо выше этой версии.
patch('app/build.gradle', (s) =>
  s.replace(/versionName\s+"[^"]*"/, `versionName "${APP_VERSION}"`));

// Saved Games (Snapshots): наш SnapshotsPlugin лежит в app-модуле и компилируется против
// play-services-games-v2. @openforge тянет тот же артефакт, но как `implementation` СВОЕГО
// модуля — на компил-classpath app он не виден, поэтому объявляем зависимость и здесь (рантайм
// один и тот же артефакт). Версия `+` — как у @openforge, чтобы Gradle свёл их к одной.
patch('app/build.gradle', (s) =>
  s.includes('play-services-games-v2') ? s
    : s.replace(/dependencies\s*\{/, 'dependencies {\n    implementation "com.google.android.gms:play-services-games-v2:+"'));

// Install Referrer: нужен чтобы знать источник трафика при установке из Play Store (attribution).
// Stable 2.2 — последняя на момент написания; pin к конкретной версии (не +), т.к. API стабильный.
patch('app/build.gradle', (s) =>
  s.includes('installreferrer') ? s
    : s.replace(/dependencies\s*\{/, 'dependencies {\n    implementation "com.android.installreferrer:installreferrer:2.2"'));

// Firebase Analytics: Google Services plugin (root build.gradle classpath)
patch('build.gradle', (s) =>
  s.includes('google-services') ? s
    : s.replace(
        /classpath 'com\.android\.tools\.build:gradle:[^']+'/,
        (m) => m + "\n        classpath 'com.google.gms:google-services:4.5.0'"));

// Firebase Analytics: apply plugin + BOM + analytics dependency (app/build.gradle)
patch('app/build.gradle', (s) => {
  let out = s;
  // apply plugin — after 'com.android.application'
  if (!out.includes('com.google.gms.google-services'))
    out = out.replace("apply plugin: 'com.android.application'",
      "apply plugin: 'com.android.application'\napply plugin: 'com.google.gms.google-services'");
  // Firebase BOM + analytics in dependencies block
  if (!out.includes('firebase-analytics'))
    out = out.replace(/dependencies\s*\{/,
      "dependencies {\n    implementation platform('com.google.firebase:firebase-bom:34.15.0')\n    implementation 'com.google.firebase:firebase-analytics'");
  return out;
});

// Crashlytics + Performance Monitoring: root build.gradle classpath (docs/play-featuring-plan.md,
// Technical Quality → "healthy releases"/crash visibility). Same Firebase project as Analytics
// above — no new console setup, just two more Gradle plugins on the already-wired google-services.json.
patch('build.gradle', (s) => {
  let out = s;
  if (!out.includes('firebase-crashlytics-gradle'))
    out = out.replace(
      /classpath 'com\.android\.tools\.build:gradle:[^']+'/,
      (m) => m + "\n        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.7'");
  if (!out.includes('com.google.firebase:perf-plugin'))
    out = out.replace(
      /classpath 'com\.android\.tools\.build:gradle:[^']+'/,
      (m) => m + "\n        classpath 'com.google.firebase:perf-plugin:2.0.2'");
  return out;
});

// Crashlytics + Performance Monitoring: apply plugins + dependencies (app/build.gradle).
// Both auto-instrument (native crash capture, network/screen-render tracing) — no custom
// Capacitor plugin/Java class needed, unlike Analytics' logEvent bridge.
patch('app/build.gradle', (s) => {
  let out = s;
  if (!out.includes('com.google.firebase.crashlytics'))
    out = out.replace("apply plugin: 'com.google.gms.google-services'",
      "apply plugin: 'com.google.gms.google-services'\napply plugin: 'com.google.firebase.crashlytics'\napply plugin: 'com.google.firebase.firebase-perf'");
  if (!out.includes('firebase-crashlytics'))
    out = out.replace("implementation 'com.google.firebase:firebase-analytics'",
      "implementation 'com.google.firebase:firebase-analytics'\n    implementation 'com.google.firebase:firebase-crashlytics'\n    implementation 'com.google.firebase:firebase-perf'");
  return out;
});

// R8 / shrink для RELEASE (docs/memory-android17.md, Фаза 3). Capacitor по умолчанию
// ставит `minifyEnabled false`, т.е. в релизе нет ни минификации кода (R8), ни отсева
// неиспользуемых ресурсов. Включаем оба + optimize-профиль ProGuard (full-mode R8 —
// дефолт AGP 8, фиксируем явно в gradle.properties ниже). ProGuard-правила для наших
// Capacitor-плагинов пишем в proguard-rules.pro (см. ниже), иначе R8 может выкинуть
// методы, которые мост зовёт рефлексией по имени. Идемпотентно (гейт по shrinkResources).
patch('app/build.gradle', (s) => {
  if (s.includes('shrinkResources')) return s;
  if (/minifyEnabled\s+false/.test(s))
    return s
      .replace(/minifyEnabled\s+false/, 'minifyEnabled true\n            shrinkResources true')
      .replace(/getDefaultProguardFile\('proguard-android\.txt'\)/,
        "getDefaultProguardFile('proguard-android-optimize.txt')");
  // релиз-блок без явного minifyEnabled — вставляем директивы в начало release { }
  return s.replace(/(buildTypes\s*\{\s*[\r\n]+\s*release\s*\{)/,
    "$1\n            minifyEnabled true\n            shrinkResources true\n" +
    "            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'");
});

// full-mode R8 — дефолт в AGP 8, но фиксируем явно (документирует намерение; защита от
// регресса, если Capacitor-шаблон когда-нибудь выставит false).
patch('gradle.properties', (s) =>
  s.includes('android.enableR8.fullMode') ? s : s.replace(/\s*$/, '\nandroid.enableR8.fullMode=true\n'));

// 2) local.properties (machine-specific SDK path; never committed)
{
  const sdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
  if (sdk) { writeFileSync(join(A, 'local.properties'), `sdk.dir=${sdk.replace(/\\/g, '/')}\n`); log('wrote: local.properties'); }
  else log('skip local.properties — set ANDROID_HOME, or open once in Android Studio');
}

// 3) Play Games app id string
patch('app/src/main/res/values/strings.xml', (s) =>
  s.includes('game_services_project_id') ? s
    : s.replace('</resources>', `    <string name="game_services_project_id">${PGS_APP_ID}</string>\n</resources>`));

// 4) AndroidManifest: Play Games APP_ID meta-data + landscape lock
patch('app/src/main/AndroidManifest.xml', (s) => {
  let out = s;
  if (!out.includes('com.google.android.gms.games.APP_ID'))
    out = out.replace('</application>',
      '        <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="@string/game_services_project_id" />\n    </application>');
  if (!/android:screenOrientation/.test(out))
    out = out.replace('<activity\n', '<activity\n            android:screenOrientation="sensorLandscape"\n');
  return out;
});

// 4b) Network security config: no cleartext, ever. Everything we talk to (Firebase, PGS,
// Capgo OTA) is already HTTPS — this just makes that explicit and closes the gap flagged in
// docs/play-featuring-plan.md (Privacy & Security → network security config not audited).
patch('app/src/main/AndroidManifest.xml', (s) =>
  s.includes('networkSecurityConfig') ? s
    : s.replace('<application\n', '<application\n        android:networkSecurityConfig="@xml/network_security_config"\n'));

{
  const dir = join(A, 'app/src/main/res/xml');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'network_security_config.xml'), NETWORK_SECURITY_CONFIG);
  log('wrote: res/xml/network_security_config.xml (cleartext disabled)');
}

// 5) Launcher icon — our art into every density, adaptive background = our image
{
  const ICON = join(ROOT, 'assets', 'icon');
  const files = {
    'ic_launcher_foreground.png': 'icon-adaptive-fg.png',
    'ic_launcher_background.png': 'icon-adaptive-bg.png',
    'ic_launcher.png': 'icon-1024.png',        // was icon-512.png; 1024² = sharper on xxxhdpi
    'ic_launcher_round.png': 'icon-1024.png',  // maskable-1024 not yet; 1024² covers all densities
  };
  let n = 0;
  for (const d of ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi']) {
    const dir = join(A, 'app/src/main/res', `mipmap-${d}`);
    if (!existsSync(dir)) continue;
    for (const [dst, src] of Object.entries(files)) copyFileSync(join(ICON, src), join(dir, dst));
    n++;
  }
  log(`icons: game art -> ${n} mipmap densities`);
  for (const xml of ['ic_launcher.xml', 'ic_launcher_round.xml'])
    patch(`app/src/main/res/mipmap-anydpi-v26/${xml}`, (s) =>
      s.replace('@color/ic_launcher_background', '@mipmap/ic_launcher_background'));
}

// 6) Fullscreen / immersive MainActivity
writeFileSync(join(A, 'app/src/main/java/com/planeflow/game/MainActivity.java'), MAIN_ACTIVITY);
log('wrote: MainActivity.java (immersive)');

// 6b) ProGuard/R8 keep-правила (release-шринк, Фаза 3) — рядом с app/build.gradle,
// который ссылается на 'proguard-rules.pro'. Перезаписываем целиком: наши правила
// самодостаточны (Capacitor-шаблонный файл — только комментарии-заготовка).
writeFileSync(join(A, 'app/proguard-rules.pro'), PROGUARD_RULES);
log('wrote: app/proguard-rules.pro (keep Capacitor plugins under R8)');

// 7) Saved Games (Snapshots) плагин — рядом с MainActivity (тот же пакет com.planeflow.game)
writeFileSync(join(A, 'app/src/main/java/com/planeflow/game/SnapshotsPlugin.java'), SNAPSHOTS_PLUGIN);
log('wrote: SnapshotsPlugin.java (Saved Games / Snapshots)');

// 8) Install Referrer плагин — attribution (UTM/referrer из Play Store, один раз при установке)
writeFileSync(join(A, 'app/src/main/java/com/planeflow/game/InstallReferrerPlugin.java'), INSTALL_REFERRER_PLUGIN);
log('wrote: InstallReferrerPlugin.java (Install Referrer attribution)');

// 9) Firebase Analytics плагин
writeFileSync(join(A, 'app/src/main/java/com/planeflow/game/FirebaseAnalyticsPlugin.java'), FIREBASE_ANALYTICS_PLUGIN);
log('wrote: FirebaseAnalyticsPlugin.java (Firebase Analytics sink)');

// 10) google-services.json → android/app/ (нужен Google Services Gradle plugin)
{
  const gservices = join(ROOT, 'google-services.json');
  if (existsSync(gservices)) {
    copyFileSync(gservices, join(A, 'app/google-services.json'));
    log('copied: google-services.json → android/app/');
  } else {
    console.warn('  WARNING: google-services.json not found at repo root — Firebase Analytics won\'t build');
  }
}

console.log('setup-android: done.');
